
// This file has been generated by the GUI designer. Do not modify.
namespace oweaselfirstrun
{
	public partial class UpdateServer
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label updateserverlabel;
		private global::Gtk.Label updateserverlb;
		private global::Gtk.Entry updateserveraddressentry;
		private global::Gtk.Button okbt;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget oweaselfirstrun.UpdateServer
			this.WidthRequest = 350;
			this.Name = "oweaselfirstrun.UpdateServer";
			this.Title = global::Mono.Unix.Catalog.GetString ("Update Server Configuration");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child oweaselfirstrun.UpdateServer.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.updateserverlabel = new global::Gtk.Label ();
			this.updateserverlabel.Name = "updateserverlabel";
			this.updateserverlabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Server Configuration");
			this.fixed1.Add (this.updateserverlabel);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.updateserverlabel]));
			w1.X = 181;
			w1.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.updateserverlb = new global::Gtk.Label ();
			this.updateserverlb.Name = "updateserverlb";
			this.updateserverlb.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Server Address:");
			this.fixed1.Add (this.updateserverlb);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.updateserverlb]));
			w2.X = 14;
			w2.Y = 74;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.updateserveraddressentry = new global::Gtk.Entry ();
			this.updateserveraddressentry.CanFocus = true;
			this.updateserveraddressentry.Name = "updateserveraddressentry";
			this.updateserveraddressentry.Text = global::Mono.Unix.Catalog.GetString ("weaseltestclient.kok.lan");
			this.updateserveraddressentry.IsEditable = true;
			this.updateserveraddressentry.InvisibleChar = '●';
			this.fixed1.Add (this.updateserveraddressentry);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.updateserveraddressentry]));
			w3.X = 155;
			w3.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.okbt = new global::Gtk.Button ();
			this.okbt.WidthRequest = 100;
			this.okbt.CanFocus = true;
			this.okbt.Name = "okbt";
			this.okbt.UseUnderline = true;
			this.okbt.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.fixed1.Add (this.okbt);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.okbt]));
			w4.X = 410;
			w4.Y = 116;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 536;
			this.DefaultHeight = 166;
			this.Show ();
			this.updateserveraddressentry.EditingDone += new global::System.EventHandler (this.OnUpdateserveraddressentryEditingDone);
			this.okbt.Released += new global::System.EventHandler (this.OnOkbtReleased);
		}
	}
}
