
// This file has been generated by the GUI designer. Do not modify.
namespace oweaselfirstrun
{
	public partial class OpenWeaselCleanup
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Label label3;
		private global::Gtk.Button closebt;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget oweaselfirstrun.OpenWeaselCleanup
			this.Name = "oweaselfirstrun.OpenWeaselCleanup";
			this.Title = global::Mono.Unix.Catalog.GetString ("OpenWeaselCleanup");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child oweaselfirstrun.OpenWeaselCleanup.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Thank you for using OpenWeasel!");
			this.fixed2.Add (this.label3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label3]));
			w1.X = 104;
			w1.Y = 65;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.closebt = new global::Gtk.Button ();
			this.closebt.WidthRequest = 100;
			this.closebt.CanFocus = true;
			this.closebt.Name = "closebt";
			this.closebt.UseUnderline = true;
			this.closebt.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.fixed2.Add (this.closebt);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.closebt]));
			w2.X = 148;
			w2.Y = 157;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.closebt.Released += new global::System.EventHandler (this.OnClosebtReleased);
		}
	}
}
