
// This file has been generated by the GUI designer. Do not modify.
namespace oweaselfirstrun
{
	public partial class Hostname
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget oweaselfirstrun.Hostname
			this.Name = "oweaselfirstrun.Hostname";
			this.Title = global::Mono.Unix.Catalog.GetString ("Hostname");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
